// This file is auto-generated by @hey-api/openapi-ts
//
// Output of @hey-api/openapi-ts 0.99.0 with its zod plugin for a CRM-shaped OpenAPI 3.1
// document (40 component schemas, CRUD operations with empty 204 responses), formatted
// with Prettier. The Zod adapter tests and scripts/benchmark-zod.ts use it as a realistic
// generated API.

import * as z from 'zod';

export const zLeadStatus = z.enum(['draft', 'open', 'qualified', 'won', 'lost', 'archived']);

export const zDealStage = z.enum([
  'prospect',
  'proposal',
  'negotiation',
  'closed_won',
  'closed_lost',
]);

export const zCurrency = z.enum(['EUR', 'USD', 'GBP']);

export const zPriority = z.enum(['low', 'medium', 'high', 'urgent']);

export const zMoney = z.object({
  amount: z.number(),
  currency: zCurrency,
});

export const zAddress = z.object({
  street: z.string(),
  number: z.string().optional(),
  box: z.string().nullish(),
  postalCode: z.string(),
  city: z.string(),
  country: z.string().length(2),
});

export const zUserSummary = z.object({
  id: z.uuid(),
  firstName: z.string(),
  lastName: z.string(),
  email: z.email(),
  avatarUrl: z.url().nullish(),
});

export const zTagResponse = z.object({
  id: z.uuid(),
  name: z.string(),
  color: z.string().regex(/^#[0-9a-f]{6}$/),
});

export const zCompanySummary = z.object({
  id: z.uuid(),
  name: z.string(),
  vatNumber: z.string().nullish(),
});

export const zCompanyResponse = z.object({
  id: z.uuid(),
  name: z.string(),
  vatNumber: z.string().nullish(),
  website: z.url().nullish(),
  address: zAddress.nullish(),
  tags: z.array(zTagResponse),
  owner: zUserSummary,
  createdAt: z.iso.datetime(),
  updatedAt: z.iso.datetime(),
});

export const zContactSummary = z.object({
  id: z.uuid(),
  firstName: z.string(),
  lastName: z.string(),
  email: z.email().nullish(),
});

export const zContactResponse = z.object({
  id: z.uuid(),
  firstName: z.string(),
  lastName: z.string(),
  email: z.email().nullish(),
  phone: z.string().nullish(),
  position: z.string().nullish(),
  company: zCompanySummary.nullish(),
  tags: z.array(zTagResponse),
  createdAt: z.iso.datetime(),
  updatedAt: z.iso.datetime(),
});

export const zLeadSource = z.string();

export const zLeadIndexResponse = z.object({
  id: z.uuid(),
  title: z.string(),
  status: zLeadStatus,
  source: zLeadSource,
  priority: zPriority,
  contact: zContactSummary.nullish(),
  company: zCompanySummary.nullish(),
  owner: zUserSummary,
  estimatedValue: zMoney.nullish(),
  createdAt: z.iso.datetime(),
});

export const zNoteResponse = z.object({
  id: z.uuid(),
  body: z.string().max(5000),
  author: zUserSummary,
  createdAt: z.iso.datetime(),
});

export const zProductResponse = z.object({
  id: z.uuid(),
  sku: z.string().regex(/^[A-Z]{3}-[0-9]{4}$/),
  name: z.string(),
  description: z.string().nullish(),
  unitPrice: zMoney,
  active: z.boolean(),
});

export const zQuoteLineResponse = z.object({
  id: z.uuid(),
  product: zProductResponse,
  quantity: z.int().gte(1),
  discountPercent: z.number().gte(0).lte(100),
  total: zMoney,
});

export const zLeadDealResponse = z.object({
  id: z.uuid(),
  title: z.string(),
  status: zLeadStatus,
  stage: zDealStage,
  value: zMoney,
  probability: z.int().gte(0).lte(100),
  expectedCloseDate: z.iso.date().nullish(),
  contact: zContactResponse.nullish(),
  company: zCompanyResponse.nullish(),
  owner: zUserSummary,
  lines: z.array(zQuoteLineResponse),
  tags: z.array(zTagResponse),
  notes: z.array(zNoteResponse),
  createdAt: z.iso.datetime(),
  updatedAt: z.iso.datetime(),
});

export const zQuoteResponse = z.object({
  id: z.uuid(),
  number: z.string(),
  deal: zLeadDealResponse,
  lines: z.array(zQuoteLineResponse),
  total: zMoney,
  validUntil: z.iso.date(),
  sentAt: z.iso.datetime().nullish(),
});

export const zInvoiceResponse = z.object({
  id: z.uuid(),
  number: z.string(),
  quote: zQuoteResponse.nullish(),
  company: zCompanyResponse,
  total: zMoney,
  paid: z.boolean(),
  dueDate: z.iso.date(),
  issuedAt: z.iso.datetime(),
});

export const zActivityType = z.enum(['call', 'meeting', 'email', 'task']);

export const zActivityResponse = z.object({
  id: z.uuid(),
  type: zActivityType,
  subject: z.string(),
  dueAt: z.iso.datetime().nullish(),
  done: z.boolean(),
  assignee: zUserSummary,
  lead: zLeadIndexResponse.nullish(),
  contact: zContactSummary.nullish(),
});

export const zPipelineStageResponse = z.object({
  id: z.uuid(),
  name: z.string(),
  order: z.int(),
  stage: zDealStage,
});

export const zPipelineResponse = z.object({
  id: z.uuid(),
  name: z.string(),
  stages: z.array(zPipelineStageResponse),
  default: z.boolean(),
});

export const zPaginationMeta = z.object({
  page: z.int().gte(1),
  perPage: z.int().gte(1).lte(100),
  total: z.int().gte(0),
});

export const zLeadIndexPage = z.object({
  data: z.array(zLeadIndexResponse),
  meta: zPaginationMeta,
});

export const zLeadDealPage = z.object({
  data: z.array(zLeadDealResponse),
  meta: zPaginationMeta,
});

export const zContactPage = z.object({
  data: z.array(zContactResponse),
  meta: zPaginationMeta,
});

export const zCompanyPage = z.object({
  data: z.array(zCompanyResponse),
  meta: zPaginationMeta,
});

export const zActivityPage = z.object({
  data: z.array(zActivityResponse),
  meta: zPaginationMeta,
});

export const zProductPage = z.object({
  data: z.array(zProductResponse),
  meta: zPaginationMeta,
});

export const zInvoicePage = z.object({
  data: z.array(zInvoiceResponse),
  meta: zPaginationMeta,
});

export const zCreateLeadRequest = z.object({
  title: z.string().min(1).max(200),
  source: zLeadSource,
  priority: zPriority,
  contactId: z.uuid().nullish(),
  companyId: z.uuid().nullish(),
  estimatedValue: zMoney.nullish(),
});

export const zUpdateLeadRequest = z.object({
  title: z.string().min(1).max(200).optional(),
  status: zLeadStatus.optional(),
  priority: zPriority.optional(),
});

export const zCreateDealRequest = z.object({
  leadId: z.uuid(),
  stage: zDealStage,
  value: zMoney,
  expectedCloseDate: z.iso.date().nullish(),
});

export const zCreateContactRequest = z.object({
  firstName: z.string(),
  lastName: z.string(),
  email: z.email().nullish(),
  phone: z.string().nullish(),
  companyId: z.uuid().nullish(),
});

export const zCreateCompanyRequest = z.object({
  name: z.string(),
  vatNumber: z.string().nullish(),
  address: zAddress.nullish(),
});

export const zCreateNoteRequest = z.object({
  body: z.string().min(1).max(5000),
});

export const zValidationErrorResponse = z.object({
  message: z.string(),
  errors: z.record(z.string(), z.array(z.string())),
});

export const zProblemResponse = z.object({
  type: z.string(),
  title: z.string(),
  status: z.int(),
  detail: z.string().nullish(),
});

/**
 * ok
 */
export const zListLeadIndexResponse = zLeadIndexPage;

export const zCreateLeadIndexBody = zCreateLeadRequest;

/**
 * ok
 */
export const zCreateLeadIndexResponse = zLeadIndexResponse;

export const zDeleteLeadIndexPath = z.object({
  id: z.uuid(),
});

/**
 * deleted
 */
export const zDeleteLeadIndexResponse = z.void();

export const zGetLeadIndexPath = z.object({
  id: z.uuid(),
});

/**
 * ok
 */
export const zGetLeadIndexResponse = zLeadIndexResponse;

export const zUpdateLeadIndexBody = zUpdateLeadRequest;

export const zUpdateLeadIndexPath = z.object({
  id: z.uuid(),
});

/**
 * updated
 */
export const zUpdateLeadIndexResponse = z.void();

/**
 * ok
 */
export const zListLeadDealResponse = zLeadDealPage;

export const zCreateLeadDealBody = zCreateDealRequest;

/**
 * ok
 */
export const zCreateLeadDealResponse = zLeadDealResponse;

export const zDeleteLeadDealPath = z.object({
  id: z.uuid(),
});

/**
 * deleted
 */
export const zDeleteLeadDealResponse = z.void();

export const zGetLeadDealPath = z.object({
  id: z.uuid(),
});

/**
 * ok
 */
export const zGetLeadDealResponse = zLeadDealResponse;

/**
 * ok
 */
export const zListContactResponse = zContactPage;

export const zCreateContactBody = zCreateContactRequest;

/**
 * ok
 */
export const zCreateContactResponse = zContactResponse;

export const zDeleteContactPath = z.object({
  id: z.uuid(),
});

/**
 * deleted
 */
export const zDeleteContactResponse = z.void();

export const zGetContactPath = z.object({
  id: z.uuid(),
});

/**
 * ok
 */
export const zGetContactResponse = zContactResponse;

/**
 * ok
 */
export const zListCompanyResponse = zCompanyPage;

export const zCreateCompanyBody = zCreateCompanyRequest;

/**
 * ok
 */
export const zCreateCompanyResponse = zCompanyResponse;

export const zDeleteCompanyPath = z.object({
  id: z.uuid(),
});

/**
 * deleted
 */
export const zDeleteCompanyResponse = z.void();

export const zGetCompanyPath = z.object({
  id: z.uuid(),
});

/**
 * ok
 */
export const zGetCompanyResponse = zCompanyResponse;

export const zCreateDealNoteBody = zCreateNoteRequest;

export const zCreateDealNotePath = z.object({
  id: z.uuid(),
});

/**
 * ok
 */
export const zCreateDealNoteResponse = zNoteResponse;

/**
 * ok
 */
export const zListActivitiesResponse = zActivityPage;

/**
 * ok
 */
export const zListProductsResponse = zProductPage;

/**
 * ok
 */
export const zListInvoicesResponse = zInvoicePage;

/**
 * ok
 */
export const zListPipelinesResponse = z.array(zPipelineResponse);

export const zGetQuotePath = z.object({
  id: z.uuid(),
});

/**
 * ok
 */
export const zGetQuoteResponse = zQuoteResponse;
