/**
 * Bundle the sandbox runtime: one classic worker script with the Mimlet packages built from
 * this repository and their pinned vendor libraries. The docs page fetches it only when a
 * visitor runs a program. Run by `prepare.ts` and `dev.ts`; `--out <dir>` also writes the
 * page-side host module for the cross-browser smoke test in tests/browser.
 */
import { createHash } from 'node:crypto';
import { mkdir, readdir, readFile, rename, rm, writeFile } from 'node:fs/promises';
import { randomUUID } from 'node:crypto';
import { resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { gzipSync } from 'node:zlib';
import { build, type InlineConfig, type Rollup } from 'vite';

const app = fileURLToPath(new URL('../', import.meta.url));
const generated = resolve(app, '.generated');

export interface SandboxRuntime {
  /** Path below the site base, for example `sandbox/runtime-0123456789.js`. */
  readonly path: string;
  readonly bytes: number;
  readonly gzipBytes: number;
  readonly sha256: string;
}

async function bundle(entry: string, format: 'iife' | 'es'): Promise<string> {
  const config: InlineConfig = {
    configFile: false,
    root: app,
    logLevel: 'warn',
    publicDir: false,
    envFile: false,
    // One copy of each vendor library: the adapters resolve theirs from the docs app too.
    resolve: { dedupe: ['zod', 'valibot'] },
    define: { 'process.env.NODE_ENV': JSON.stringify('production') },
    build: {
      write: false,
      target: 'es2022',
      minify: 'esbuild',
      sourcemap: false,
      reportCompressedSize: false,
      copyPublicDir: false,
      rollupOptions: {
        // Zod 4.6 places explanatory comments next to its pure annotations. Rollup drops
        // those comments, which is harmless, and would otherwise warn on every build.
        onwarn(warning, warn) {
          if (warning.code !== 'INVALID_ANNOTATION') {
            warn(warning);
          }
        },
      },
      lib: {
        entry: resolve(app, entry),
        formats: [format],
        name: 'MimletSandbox',
        fileName: () => 'bundle.js',
      },
    },
  };
  // Vite's build sets NODE_ENV=production for the whole process. dev.ts starts the
  // VitePress dev server afterwards, which must not inherit it.
  const environment = process.env.NODE_ENV;
  let result: Awaited<ReturnType<typeof build>>;
  try {
    result = await build(config);
  } finally {
    if (environment === undefined) {
      delete process.env.NODE_ENV;
    } else {
      process.env.NODE_ENV = environment;
    }
  }
  const outputs = (Array.isArray(result) ? result : [result]) as Rollup.RollupOutput[];
  const chunks = outputs.flatMap((output) => output.output).filter((item) => item.type === 'chunk');
  if (chunks.length !== 1 || !chunks[0]) {
    throw new Error(`Expected one sandbox chunk for ${entry}, got ${chunks.length}`);
  }
  return chunks[0].code;
}

async function writeChanged(path: string, content: string): Promise<void> {
  if (
    await readFile(path, 'utf8').then(
      (value) => value === content,
      () => false
    )
  ) {
    return;
  }
  const temporary = `${path}.${randomUUID()}.tmp`;
  await writeFile(temporary, content);
  await rename(temporary, path);
}

export async function buildSandboxRuntime(): Promise<SandboxRuntime> {
  const code = await bundle('sandbox/worker.ts', 'iife');
  const sha256 = createHash('sha256').update(code).digest('hex');
  const name = `runtime-${sha256.slice(0, 12)}.js`;
  const directory = resolve(generated, 'public/sandbox');
  await mkdir(directory, { recursive: true });
  for (const file of await readdir(directory)) {
    if (file !== name && /^runtime-[0-9a-f]+\.js$/.test(file)) {
      await rm(resolve(directory, file), { force: true });
    }
  }
  await writeChanged(resolve(directory, name), code);
  const runtime: SandboxRuntime = {
    path: `sandbox/${name}`,
    bytes: Buffer.byteLength(code),
    gzipBytes: gzipSync(code).length,
    sha256,
  };
  await writeChanged(
    resolve(generated, 'sandbox-runtime.ts'),
    `// Generated by scripts/sandbox-runtime.ts.\nexport const sandboxRuntime = ${JSON.stringify(runtime, null, 2)} as const;\n`
  );
  console.log(
    `Sandbox runtime: ${runtime.path}, ${(runtime.bytes / 1024).toFixed(1)} KiB, ${(runtime.gzipBytes / 1024).toFixed(1)} KiB gzip.`
  );
  return runtime;
}

/** Writes `runtime.js` and the page-side `host.js` for tests outside the docs site. */
export async function writeSandboxBundles(directory: string): Promise<void> {
  await mkdir(directory, { recursive: true });
  await writeFile(resolve(directory, 'runtime.js'), await bundle('sandbox/worker.ts', 'iife'));
  await writeFile(resolve(directory, 'host.js'), await bundle('sandbox/index.ts', 'es'));
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const args = process.argv.slice(2);
  if (args.length === 2 && args[0] === '--out' && args[1]) {
    await writeSandboxBundles(resolve(args[1]));
  } else if (args.length === 0) {
    await buildSandboxRuntime();
  } else {
    throw new TypeError('Usage: sandbox-runtime.ts [--out <directory>]');
  }
}
