import { declarationInputs } from './schema-types.js';
import { compile } from 'json-schema-to-typescript';
import type { JsonSchema, JsonSchemaOptions } from '@mimlet/json-schema';
import { jsonSchemaAdapter } from '@mimlet/json-schema';

export interface GeneratedFile {
  readonly path: string;
  readonly content: string;
}
export interface ModuleReference {
  readonly module: string;
  readonly export: string;
}
export interface BuilderTarget {
  readonly name: string;
  readonly source: ModuleReference & {
    readonly kind:
      | 'factory'
      | 'builder'
      | 'standard-json-schema'
      | 'typebox'
      | 'typebox-legacy'
      | 'valibot'
      | 'effect'
      | 'standard-schema';
    readonly factory?: ModuleReference;
  };
  readonly fields?: ReadonlyArray<string | { readonly property: string; readonly method: string }>;
}
export interface EmitOptions {
  readonly runtimeModule?: string;
  readonly select?: ReadonlyArray<string>;
}
export interface JsonBuilderTarget {
  readonly name: string;
  readonly schema: JsonSchema;
  /** Data-only settings; executable providers and custom callbacks are not serialized. */
  readonly options?: Pick<
    JsonSchemaOptions,
    | 'dialect'
    | 'profile'
    | 'references'
    | 'maxArrayLength'
    | 'maxStringLength'
    | 'maxValueDepth'
    | 'maxAttempts'
  >;
}
const header = '// Generated by Mimlet. Edit the source/configuration, not this file.\n';
const forbidden = new Set(
  'break case catch class const continue debugger default delete do else enum export extends false finally for function if import in instanceof new null return super switch this throw true try typeof var void while with implements interface let package private protected public static yield await'.split(
    ' '
  )
);
const methods = new Set(
  'constructor then __proto__ prototype build buildList buildAsync buildListAsync buildValidated buildValidatedList buildValidatedAsync buildValidatedListAsync transform transformAsync with withFactory replace replaceFactory omit describe usingValidation'.split(
    ' '
  )
);
const json = (value: unknown) => JSON.stringify(value);
export class CodegenError extends Error {
  readonly code = 'CODEGEN_FAILED';
  constructor(message: string, options?: ErrorOptions) {
    super(message, options);
    this.name = 'CodegenError';
  }
}
function identifier(name: string): string {
  if (
    typeof name !== 'string' ||
    !/^[A-Za-z_$][A-Za-z0-9_$]{0,127}$/.test(name) ||
    forbidden.has(name)
  ) {
    throw new CodegenError(
      'Expected a non-reserved JavaScript identifier of at most 128 characters'
    );
  }
  return name;
}
function moduleName(name: string): string {
  if (typeof name !== 'string' || !name.trim() || name.length > 2048 || /[\0\r\n]/.test(name)) {
    throw new CodegenError('Expected a nonempty module specifier without control characters');
  }
  return name;
}
function reference(value: ModuleReference, local: string): string {
  if (!value || typeof value !== 'object') {
    throw new CodegenError('Expected a module reference');
  }
  const exported = value.export === 'default' ? 'default' : identifier(value.export);
  return `import { ${exported} as ${local} } from ${json(moduleName(value.module))};\n`;
}
/**
 * The local, unexported type of a generated `withX()` parameter, as the Hey API plugin emits it:
 * never for object unions, which need a whole `replace()`. Otherwise exactly what `with()`
 * accepts for that key, as in core `fluent()`: indexed access adds `undefined` to every optional
 * key, so keep it only where the property accepts it (respecting `exactOptionalPropertyTypes`).
 * `NonNullable` keeps a nullable root's helpers typechecking; they are `never` anyway.
 * `declared` holds the file's other declarations, so the alias name never shadows one.
 */
function setterType(declared: string): { readonly name: string; readonly declaration: string } {
  let name = 'BuilderSetterValue';
  for (let n = 2; new RegExp(`\\b${name}\\b`).test(declared); n++) {
    name = `BuilderSetterValue${n}`;
  }
  return {
    name,
    declaration: `// What with() accepts for one property: an exact optional key is omitted, never set to undefined.\ntype ${name}<T, K extends keyof NonNullable<T>> = BuilderPatch<T> extends never\n  ? never\n  : { [P in K]: undefined } extends Pick<NonNullable<T>, K>\n    ? NonNullable<T>[K]\n    : Exclude<NonNullable<T>[K], undefined>;\n`,
  };
}
function helpers(fields: BuilderTarget['fields'], input: string, setter: string): string {
  if (fields === undefined) {
    return '';
  }
  if (!Array.isArray(fields) || fields.length > 1000) {
    throw new CodegenError('Expected at most 1000 fields');
  }
  const used = new Set(methods);
  const properties = new Set<string>();
  return fields
    .map((field) => {
      const property = typeof field === 'string' ? field : field?.property;
      if (typeof property !== 'string' || property.length > 1000 || properties.has(property)) {
        throw new CodegenError('Fields must have unique string property names');
      }
      properties.add(property);
      const suffix =
        property
          .split(/[^A-Za-z0-9]+/)
          .filter(Boolean)
          .map((part) => part[0]!.toUpperCase() + part.slice(1))
          .join('') || 'Value';
      const explicit = typeof field === 'object';
      let method = explicit ? identifier(field.method) : `with${suffix}`;
      if (explicit && used.has(method)) {
        throw new CodegenError('An explicit field method conflicts with another capability');
      }
      for (let n = 2; used.has(method); n++) {
        method = `with${suffix}${n}`;
      }
      used.add(method);
      // The parameter type is the contract: unions cannot be partially switched, unknown fields
      // fail to typecheck. The cast covers shapes whose patch is not a plain `Partial`.
      return `  ${method}(value: ${setter}<${input}, ${json(property)}>): this {\n    return this.with({ [${json(property)}]: value } as BuilderPatch<${input}>);\n  }\n`;
    })
    .join('');
}
function selected<T extends { readonly name: string }>(
  targets: readonly T[],
  options: EmitOptions
): T[] {
  if (!Array.isArray(targets) || targets.length > 1000) {
    throw new CodegenError('Expected at most 1000 builder targets');
  }
  const names = new Set<string>();
  for (const target of targets) {
    identifier(target?.name);
    const key = target.name.toLowerCase();
    if (names.has(key)) {
      throw new CodegenError('Builder names must be unique on case-insensitive filesystems');
    }
    names.add(key);
  }
  if (
    options.select !== undefined &&
    (!Array.isArray(options.select) ||
      options.select.some((name) => !targets.some((target) => target.name === name)))
  ) {
    throw new CodegenError('Selection contains an unknown target');
  }
  return targets
    .filter((target) => options.select === undefined || options.select.includes(target.name))
    .sort((a, b) => (a.name < b.name ? -1 : a.name > b.name ? 1 : 0));
}
/** Emit module-based builders without importing or executing application modules. */
export function emitBuilders(
  targets: readonly BuilderTarget[],
  options: EmitOptions = {}
): GeneratedFile[] {
  const runtime = moduleName(options.runtimeModule ?? '@mimlet/core');
  return selected(targets, options).map((target) => {
    const source = target.source;
    let imports = reference(source, 'source');
    let expression: string;
    switch (source.kind) {
      case 'factory':
        imports += `import { createBuilder } from ${json(runtime)};\n`;
        expression = 'createBuilder(source)';
        break;
      case 'builder':
        expression = 'source';
        break;
      case 'standard-schema':
        imports += reference(source.factory!, 'factory');
        imports += `import { createSchemaBuilder } from ${json(runtime)};\n`;
        expression = 'createSchemaBuilder(source, factory)';
        break;
      default: {
        const adapters = {
          'standard-json-schema': ['json-schema', 'fromStandardJsonSchema'],
          typebox: ['typebox', 'fromTypeBox'],
          'typebox-legacy': ['typebox-legacy', 'fromTypeBox'],
          valibot: ['valibot', 'fromValibot'],
          effect: ['effect', 'fromEffect'],
        } as const;
        const adapter = adapters[source.kind];
        if (!adapter) {
          throw new CodegenError('Unsupported source kind');
        }
        imports += `import { ${adapter[1]} as fromSchema } from ${json(`@mimlet/${adapter[0]}`)};\n`;
        expression = 'fromSchema(source)';
      }
    }
    const setter = setterType(target.name);
    const methods = helpers(target.fields, 'Input', setter.name);
    const content = `${header}${imports}import { builderClass, type BuilderPatch } from ${json(runtime)};\n\nconst definition = () => ${expression};\ntype Input = Awaited<ReturnType<ReturnType<typeof definition>["buildAsync"]>>;\n${methods && setter.declaration}const Base = builderClass(definition);\nexport class ${target.name} extends Base {\n${methods}}\n`;
    return { path: `${target.name}.ts`, content };
  });
}
/** Generate types and fixtures from the SAME validated schema, not an unrelated generic assertion. */
export async function emitJsonSchemaBuilders(
  targets: readonly JsonBuilderTarget[],
  options: EmitOptions = {}
): Promise<GeneratedFile[]> {
  const runtime = moduleName(options.runtimeModule ?? '@mimlet/core');
  const files: GeneratedFile[] = [];
  for (const target of selected(targets, options)) {
    if (target.options !== undefined) {
      const allowed = new Set([
        'dialect',
        'profile',
        'references',
        'maxArrayLength',
        'maxStringLength',
        'maxValueDepth',
        'maxAttempts',
      ]);
      if (
        !target.options ||
        typeof target.options !== 'object' ||
        Array.isArray(target.options) ||
        Reflect.ownKeys(target.options).some(
          (key) =>
            typeof key !== 'string' ||
            !allowed.has(key) ||
            !('value' in Object.getOwnPropertyDescriptor(target.options!, key)!)
        )
      ) {
        throw new CodegenError('JSON generation settings must be data-only supported options');
      }
    }
    // Preparation enforces the supported data/vocabulary/budget contract before the type compiler.
    const adapter = jsonSchemaAdapter(target.schema, target.options);
    const schema = adapter.source;
    const name = `${target.name}Input`;
    let declarations: string;
    if (typeof schema === 'boolean') {
      declarations = `export type ${name} = ${schema ? 'unknown' : 'never'};\n`;
    } else {
      const declared = declarationInputs(
        schema,
        JSON.parse(json(target.options?.references ?? {})),
        adapter.metadata.dialect
      );
      const input = declared.schema as Record<string, unknown>;
      input.title = name;
      // TypeScript declarations are structural approximations; original runtime validation remains mandatory.
      try {
        declarations = await compile(input, name, {
          bannerComment: '',
          format: true,
          unknownAny: true,
          enableConstEnums: false,
          maxItems: 20,
          $refOptions: {
            resolve: {
              file: false,
              http: false,
              memory: {
                order: 1,
                canRead: (file: { url: string }) => Object.hasOwn(declared.references, file.url),
                read: (file: { url: string }) => {
                  const found = declared.references[file.url];
                  if (found === undefined) {
                    throw new CodegenError('A type reference was not supplied in memory');
                  }
                  return json(found);
                },
              },
            },
          },
        });
      } catch (cause) {
        throw new CodegenError('Schema type emission failed', { cause });
      }
    }
    const fields =
      typeof schema === 'object' && schema.properties && typeof schema.properties === 'object'
        ? Object.keys(schema.properties).sort()
        : [];
    const setter = setterType(`${target.name}\n${declarations}`);
    const methods = helpers(fields, name, setter.name);
    const content = `${header}import { builderClass, type BuilderPatch, type SchemaBuilder, type GenerationSession } from ${json(runtime)};\nimport { fromJsonSchema } from "@mimlet/json-schema";\n\n${declarations}\nconst schema = ${json(schema)};\nconst options = ${json(target.options ?? {})} as const;\nconst definition = () => fromJsonSchema(schema, options) as SchemaBuilder<${name}, ${name}, [session?: GenerationSession]>;\n${methods && setter.declaration}const Base = builderClass(definition);\nexport class ${target.name} extends Base {\n${methods}}\n`;
    files.push({ path: `${target.name}.ts`, content });
  }
  return files;
}
