import { mkdtemp, readFile, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { expect, it } from 'vitest';
import * as fc from 'fast-check';
import legacy from '../fixtures/pre-mimlet.json';
import {
  restoreFixture,
  restoreSession,
  SessionReplayError,
} from '../../packages/core/src/index.js';
import type { SessionSnapshot } from '../../packages/core/src/index.js';
import { replayFixtureProperty } from '../../packages/fast-check/src/index.js';
import type { PropertyReplay } from '../../packages/fast-check/src/index.js';
import { emitBuilders, writeGenerated } from '../../packages/codegen/src/index.js';
import type { BuilderTarget } from '../../packages/codegen/src/index.js';

// Captured by the actual pre-rename distribution at the commit recorded in this fixture.
it('resumes pre-Mimlet random streams, sequences and native fixture values', () => {
  const session = restoreSession(legacy.snapshot as unknown as SessionSnapshot, legacy.identity);
  expect(session.random()).toBe(legacy.expected.random);
  expect(session.sequence('id', 10)).toBe(legacy.expected.id);
  expect(() =>
    restoreSession(legacy.snapshot as unknown as SessionSnapshot, {
      ...legacy.identity,
      provider: 'a-different-provider',
    })
  ).toThrow(SessionReplayError);
  const value = restoreFixture(legacy.captured) as {
    created: Date;
    user: { id: bigint };
    owner: { id: bigint };
  };
  expect(value.created.toISOString()).toBe('2026-01-01T00:00:00.000Z');
  expect(value.user.id).toBe(42n);
  expect(value.owner).toBe(value.user);
});

it('replays pre-Mimlet property failures with the same counterexample', () => {
  const result = replayFixtureProperty(
    fc.integer({ min: 1, max: 10000 }),
    (value) => value < 10,
    legacy.property as PropertyReplay,
    legacy.identity
  );
  expect(result.details.failed).toBe(true);
  expect(result.details.counterexample).toEqual(legacy.counterexample);
});

// After 0.1.0-beta.0, named setters take exactly what with() accepts for their property (an exact
// optional key rejects undefined) through one local type. Method names and bodies are unchanged.
const setterType = `// What with() accepts for one property: an exact optional key is omitted, never set to undefined.
type BuilderSetterValue<T, K extends keyof NonNullable<T>> = BuilderPatch<T> extends never
  ? never
  : { [P in K]: undefined } extends Pick<NonNullable<T>, K>
    ? NonNullable<T>[K]
    : Exclude<NonNullable<T>[K], undefined>;
`;

it('preserves generated fluent APIs and ownership when imports are renamed', async () => {
  const generated = emitBuilders(legacy.targets as BuilderTarget[]);
  expect(generated).toEqual(
    legacy.generated.map((file) => ({
      ...file,
      content: file.content
        .replaceAll('@jeffreynijs/test-builders-', '@mimlet/')
        .replaceAll('@jeffreynijs/test-builders', '@mimlet/core')
        .replace('Generated by test-builders.', 'Generated by Mimlet.')
        .replace('const Base =', `${setterType}const Base =`)
        .replaceAll(
          /BuilderPatch<Input> extends never \? never : NonNullable<Input>\[("\w+")\]/g,
          'BuilderSetterValue<Input, $1>'
        ),
    }))
  );
  const directory = await mkdtemp(join(tmpdir(), 'mimlet-migration-'));
  try {
    for (const file of legacy.generated) {
      await writeFile(join(directory, file.path), file.content);
    }
    await writeFile(
      join(directory, '.test-builders.manifest.json'),
      JSON.stringify(legacy.ownership)
    );
    await writeFile(join(directory, 'handwritten.ts'), '// keep me');
    // Older emitter output is owned and unedited: --check reports drift, generate rewrites it.
    const checked = await writeGenerated(directory, generated, { check: true });
    expect(checked.clean).toBe(false);
    expect(checked.modified).toEqual([]);
    expect(checked.changed).toEqual(generated.map((file) => file.path).sort());
    expect(await readFile(join(directory, legacy.generated[0]!.path), 'utf8')).toBe(
      legacy.generated[0]!.content
    );
    await writeGenerated(directory, generated);
    expect((await writeGenerated(directory, generated, { check: true })).clean).toBe(true);
    for (const file of generated) {
      expect(await readFile(join(directory, file.path), 'utf8')).toBe(file.content);
    }
    expect(await readFile(join(directory, 'handwritten.ts'), 'utf8')).toBe('// keep me');
  } finally {
    await rm(directory, { recursive: true, force: true });
  }
});
